MAX_N = 100
MAX_N_TO_BE_OPTIMISED = 8
#works best with 10
SEQUENTIVE_EQUAL_DISTANCE_OCCURANCES_FOR_EXTREMUM_REACHED = 40

TIMES_OF_EXECUTION_OF_ALGORITHM = 1000
TENTH_STEP_OF_EXECUTION_COUNT = 990
TWENTIETH_STEP_OF_EXECUTION_COUNT = 980
THIRTIETH_STEP_OF_EXECUTION_COUNT = 970
FOURTIETH_STEP_OF_EXECUTION_COUNT = 960