MAX_N = 100
MAX_N_TO_BE_OPTIMISED = 8
#works best with 10
SEQUENTIVE_EQUAL_DISTANCE_OCCURANCES_FOR_EXTREMUM_REACHED = 70

TIMES_OF_EXECUTION_OF_ALGORITHM = 500
TENTH_STEP_OF_EXECUTION_COUNT = 490
HUNDRED_STEP_OF_EXECUTION_COUNT = 400
TWO_HUNDRED_STEP_OF_EXECUTION_COUNT = 300
THREE_HUNDRED_STEP_OF_EXECUTION_COUNT = 200