PLAYER_IS_FIRST_VALUE = '1'
COMPUTER_IS_FIRST_VALUE = '0'

EMPTY_POSITION_ON_BOARD_CHAR = '_'
PLAYER_SIGN_ON_BOARD_CHAR = 'X'
COMPUTER_SIGN_ON_BOARD_CHAR = 'O'
BOARD_FINAL_STATE_CHAR = '.'


INITIAL_VERSION_OF_BOARD = [[EMPTY_POSITION_ON_BOARD_CHAR for i in range(3)] for i in range(3)]

UPPER_LABEL_OF_PRINTING_BOARD_STRING = "  0 1 2"

PLAYER_IS_ON_TURN_STRING = "PLAYER"
COMPUTER_IS_ON_TURN_STRING = "COMPUTER"
